### ISSUE TITLE
Aggiornare README.md

### ISSUE THREAD

**Issue by gbonanome** [Aubreymcfato/aaronswartz#22]
Una piccola scocciatura di [gitbook](https://github.com/GitbookIO/gitbook) consiste nel fatto che obbliga ad usare un file README.md come introduzione del libro (gente che si lamenta [qui](https://github.com/GitbookIO/gitbook/issues/392) e [qui](https://github.com/GitbookIO/gitbook/issues/476)).
Purtroppo è la stessa cosa che viene mostrata in apertura del repository qui su GitHub. Secondo te, @Aubreymcfato, sarebbe possibile editare il frontespizio per renderlo più "generico"? Basterebbe anche solo una riga con scritto "Per collaborare all'ebook vai qui" (con link al [wiki](https://github.com/Aubreymcfato/aaronswartz/wiki)).
Sarebbe anche interessante integrare nel frontespizio gli update lasciati sull'homepage del tumblr secondo me.

**Comment by Aubreymcfato** [comment]
Ci provo.
