### ISSUE TITLE
Allineamento immagini e paragrafo

### ISSUE THREAD

**Issue by gbonanome** [Aubreymcfato/aaronswartz#23]
Sarebbe carino allineare il testo accanto alle immagini che compaiono nei capitoli. A quanto pare in una prossima versione gitbook permetterà di aggiungere fogli di stile personalizzati nel suo workflow (vedi https://github.com/GitbookIO/gitbook/pull/555).
Una volta rilasciata possiamo aggiungere un foglio di stile con questa semplice regola (oppure con qualcosa di più furbo se si intende aggiungere altre immagini in futuro)

```
.page-inner p img:first-child {
    float: left;
    margin-right: 20px;
}
```

**Comment by gbonanome** [comment]
Tra l'altro, come nota spiritosa personale, segnalo che avevo già committato dentro a [book.json](https://github.com/Aubreymcfato/aaronswartz/blob/master/book.json#L55) parte del fix, salvo accorgermi che la feature era stata introdotta su gitbook poche ore fa e non ancora rilasciata :sweat_smile:

**Comment by Aubreymcfato** [comment]
Aspettiamo quindi che sia rilasciata?

**Comment by gbonanome** [comment]
Sì sì. Tra l'altro hanno anche già aggiornato la documentazione, quindi mi aspetto sia una cosa di giorni.
